# Site settings
title: Utah Mapping Portal
email: agrc@utah.gov
description: Utah Mapping Portal | The Utah Automated Geographic Reference Center
baseurl: ""
url: "https://gis.utah.gov"
highlighter: rouge
twitter_username: MapUtah
github_username: agrc
facebook_username: UtahAGRC
vimeo_username: utahagrc
permalink: /:title/
production_url: 'https://gis.utah.gov'
analytics:
    google:
        tracking_id: 'UA-11849964-41'
sass:
    style: compressed
github:
    repository_url: https://github.com/agrc/agrc.github.io
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    hard_wrap: false
timezone: America/Denver
exclude: [
    "node_modules",
    "scripts/cleanser.py",
    "scripts/cleanser.pyc",
    "scripts/datatable.py",
    "scripts/datatable.pyc",
    "scripts/tests.py",
    "scripts/tests.pyc",
    "Gemfile.lock",
    "Gemfile",
    "GruntFile.js",
    "bower.json",
    "package.json",
    "*.bak",
    "README.md",
    "docker-compose.yml",
    "LICENSE"
]
include: [
    "_redirects"
    "_headers"
]
